#!/bin/sh

### BEGIN INIT INFO
# Provides:          wgetstack
# Required-Start:    $remote_fs
# Required-Stop:  	0 1 2		
# Default-Start:     S
# Default-Stop:
# Short-Description: wgetstack
# Description:       download manager
### END INIT INFO

. /lib/lsb/init-functions

[ -f /etc/default/rcS ] && . /etc/default/rcS
PATH=/bin:/usr/bin:/sbin:/usr/sbin:/home/mia/.usr/bin
PROGRAM=/home/mia/.usr/bin/wget_download.sh
READ_FILE=/home/mia/fordownload
DOWNLOAD_DIR=/media/DATA2
LOG_DIR=/home/mia/
LOG_FILE=.wgetstak.log
LOG_OVER_FILE=.wgetover.log



case "$1" in
  start)
	log_begin_msg "Start wget manager"      
        sh $PROGRAM $READ_FILE $DOWNLOAD_DIR $LOG_DIR $LOG_FILE $LOG_OVER_FILE > /dev/null &
	log_end_msg 0
	;;
  stop)
	;;
  force-reload|restart)
	$0 start
	;;
  status)
	exit 0
	;;
  *)
	log_success_msg "Usage: /etc/init.d/lm-sensors {start|stop|restart|force-reload|status}"
	exit 1
esac

exit 0
